FROM ubuntu:latest

ENV TZ=Europe/Moscow
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt update && apt install -y apache2 php libapache2-mod-php php-mysql 
 
ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data 
ENV APACHE_LOG_DIR /var/log/apache2
ENV APACHE_RUN_DIR /var/www/html

RUN mkdir -p $APACHE_RUN_DIR && chown -R $APACHE_RUN_USER:$APACHE_RUN_GROUP $APACHE_RUN_DIR

EXPOSE 80
ENTRYPOINT ["/usr/sbin/apache2"]
CMD ["-D", "FOREGROUND"]
